### ISSUE TITLE
can not find jars

### ISSUE THREAD

**Issue by hktalent** [pwntester/SerialKillerBypassGadgetCollection#1]
where find:
com.ibm.jaxws.thinclient_8.5.0.jar
com.ibm.ws.ejb.embeddableContainer_8.5.0.jar
com.oracle.weblogic.iiop-common.jar
com.ibm.mq.jmqi.jar
com.ibm.ws.ejb.thinclient_8.5.0.jar
com.ibm.msg.client.jms.jar
com.ibm.ws.runtime.coregroupbridge.jar

thanks

**Comment by pwntester** [comment]
As explained in the README:

```
The following Jar files are required from Weblogic and WebSphere application servers and not distributed with SerialKiller Bypass Gadget Collection. Copy them from your authorized version of the application server to the /external directory.```

You need to get a copy of these application servers and then just `find` the jars
